controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      constraints:
        stopped_velocity_tolerance: 0.02
        goal_time: 0.0
        joint1:
          trajectory: 0.05
          goal: 0.02
        joint2:
          trajectory: 0.05
          goal: 0.02
        joint3:
          trajectory: 0.05
          goal: 0.02
        joint4:
          trajectory: 0.05
          goal: 0.02
        joint5:
          trajectory: 0.05
          goal: 0.02
        joint6:
          trajectory: 0.05
          goal: 0.02
